export const metadata = {
  title: 'Your App',
  description: 'Generated by Next.js',
};

import '../globals.css'; // if you have global styles
import AdminLayout from "@/components/layouts/AdminLayout";
import Protectedlayout from "@/components/layouts/ProtechtedLayout";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Protectedlayout access={[ 'admin']}>
          <AdminLayout>{children}</AdminLayout>
        </Protectedlayout>
      </body>
    </html>
  );
}
